name: Workflow for checking http status codes

on: [push]

jobs:
  build:
    name: HTTP Status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Check HTTP status of production site
        id: http_status
        uses: ./
        with:
          sites: '["http://github.com", "https://education.github.com","https://www.jammgen3mandats.org"]'
          expected: '[301, 200, 200]'
      
      - name: Print failed sites
        if: failure()
        run: echo "${{ steps.http_status.outputs.failed_sites }}"